---
title: "Assignment 5"
subtitle: "612203012"
output:
  pdf_document: default
  html_notebook: default
header-includes:
  \usepackage{fvextra}
  \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---
\fontfamily{cmr}
\fontsize{13}{23}
\fontseries{b}
\selectfont

\

# Q1:

```{r}
#Solution: Here we want to test Ho: mu = 73000 vs H1: mu < 73000
x = c(70000, 78000, 62000, 66000, 61000, 72000, 58000, 64000, 60000, 73000, 74000, 76000)
t.test(x, mu = 73000, alternative = "less")
#Conclusion: Here we observe that the level of significance 5% is greater than p-value = 0.01193, so we reject Ho. Hence we conclude average monthly salary has gone below 73000.
```

\

# Q2:

```{r}
#Solution: Here we want to test Ho: sigma1^2=sigma2^2 vs H1: sigma1^2<sigma2^2
x = c(20, 16, 26, 27, 23, 22, 25)
y = c(27, 33, 42, 35, 32, 34, 38, 29, 40)
var.test(x, y, alternative = "less", conf.level = 0.95)
#Conclusion: Here we observe that the level of significance 5% is less than p-value = 0.2752, so we accept Ho. Hence we conclude that variability in time taken by Machine I is the same as that of Machine II.
```

\

# Q3:

```{r}
#Solution: Here we want to test Ho: mu = 52 vs H1: mu > 52
x = c(57, 60, 54, 52, 58, 61, 59, 54, 57, 62)
t.test(x, mu = 52, alternative = "greater")
#Conclusion: Here we observe that the level of significance 5% is greater than p-value = 0.0002755, so we reject Ho. Hence we conclude that the average height of female students is greater than 52 inches.
```

\

# Q4:

```{r}
#Solution: Here we want to test Ho: mu = 120 vs H1: mu < 120
n = 100
xb = 105
sd = 20
muo = 120
z = (xb - muo)/(sd/sqrt(n))
pv = pnorm(z, 0, 1)
pv
#Conclusion: Here we observe that the level of significance 5% is greater than p-value = 3.190892e-14, so we reject Ho. Hence we conclude that the batch does not meet the specification.
```

\

# Q5:

```{r}
#Solution: Here we want to test Ho: mu = 100 vs H1: mu is not equal to 100
x = c(70, 120, 110, 101, 88, 83, 95, 89, 107, 125)
t.test(x, mu = 100)
#Conclusion: Here we observe that the level of significance 5% is less than p-value = 0.8296, so we accept Ho. Hence we conclude that the population mean IQ is 100.
```

\

# Q6:

```{r}
#Solution: Here we want to test Ho: mu = 70 vs H1: mu > 70
n = 100
xb = 71.8
sd = 8.9
muo = 70
z = (xb - muo)/(sd/sqrt(n))
pv = pnorm(z, 0, 1, lower.tail = F)
pv
#Conclusion: Here we observe that the level of significance 5% is greater than p-value = 0.02156381, so we reject Ho. Hence we conclude that the mean life span today is equal to 70 years.
```

\

# Q7:

```{r}
#Solution: Here we want to test Ho: mu = 8 vs H1: mu is not equal to 8
n = 50
xb = 7.8
sd = 0.5
muo = 8
z = (xb - muo)/(sd/sqrt(n))
pv = 2*pnorm(abs(z), 0, 1, lower.tail = F)
pv
#Conclusion: Here we observe that the given level of significance 1% is greater than p-value = 0.004677735, so we reject Ho. Hence we conclude that mean breaking strength is not 8 kg.
```

\

# Q8:

```{r}
#Solution: Here we want to test Ho: sigma1^2=sigma2^2 vs H1: sigma1^2>sigma2^2
x = c(6, 9, 4, 1, 9, 9, 3, 4, 10)
y = c(5, 7, 4, 1, 8, 7, 4, 3, 9)
var.test(x, y, alternative = "greater", conf.level = 0.95)
#Conclusion: Here we observe that the level of significance 5% is less than p-value = 0.2684, so we accept Ho. Hence we conclude that the variability in time taken by Expert I is the same as that of Expert II.
```

\

# Q9:

```{r}
#Solution: Here we want to test Ho: mu = 42000 vs H1: mu > 42000
n = 30
xb = 43260
sd = 5230
muo = 42000
z = (xb - muo)/(sd/sqrt(n))
pv = pnorm(z, 0, 1, lower.tail = F)
pv
#Conclusion: Here we observe that the given level of significance 5% is less than p-value = 0.09349081, so we accept Ho. Hence we conclude that assistant professor earn more than $42,000 per year on average.
```

\

# Q10:

```{r}
#Solution: Here we want to test Ho: sigma1^2=sigma2^2 vs H1: sigma1^2 is not equal to sigma2^2
x = c(13, 15, 18, 20, 22, 9, 16)
y = c(21, 18, 20, 16, 9)
var.test(x, y, conf.level = 0.95)
#Conclusion: Here we observe that the given level of significance 5% is less than p-value = 0.8099, so we accept Ho. Hence we conclude that sigma1^2 = sigma2^2.
```